using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Long.Metadata.Generator;

[Generator(LanguageNames.CSharp)]
public sealed class GeneratedMetadataGenerator : IIncrementalGenerator
{
    private const string GeneratedMetadataAttributeName = "Long.Metadata.GeneratedMetadataAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var properties = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is PropertyDeclarationSyntax { AttributeLists.Count: > 0 },
                static (ctx, cancellationToken) => GetMetadataProperties(ctx, cancellationToken))
            .SelectMany(static (items, _) => items)
            .Collect();

        context.RegisterSourceOutput(properties, static (context, items) =>
        {
            var distinct = items
                .GroupBy(static item => item.Key)
                .Select(static group => group.First())
                .OrderBy(static item => item.AttributeTypeFullName, StringComparer.Ordinal)
                .ThenBy(static item => item.DeclaringTypeFullName, StringComparer.Ordinal)
                .ThenBy(static item => item.PropertyName, StringComparer.Ordinal)
                .ToImmutableArray();

            context.AddSource("Long.Metadata.GeneratedMetadata.g.cs", GenerateSource(distinct));
        });
    }

    private static ImmutableArray<MetadataProperty> GetMetadataProperties(GeneratorSyntaxContext context, CancellationToken cancellationToken)
    {
        var propertyDeclaration = (PropertyDeclarationSyntax)context.Node;
        if (context.SemanticModel.GetDeclaredSymbol(propertyDeclaration, cancellationToken) is not IPropertySymbol property)
        {
            return ImmutableArray<MetadataProperty>.Empty;
        }

        var builder = ImmutableArray.CreateBuilder<MetadataProperty>();

        foreach (var attribute in property.GetAttributes())
        {
            var attributeType = attribute.AttributeClass;
            if (attributeType is null || !InheritsFromGeneratedMetadata(attributeType))
            {
                continue;
            }

            builder.Add(new MetadataProperty(
                Key: $"{attributeType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}|{property.ContainingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}|{property.Name}",
                AttributeTypeCodeName: attributeType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                AttributeTypeFullName: attributeType.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat),
                DeclaringTypeCodeName: property.ContainingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                DeclaringTypeFullName: property.ContainingType.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat),
                DeclaringTypeDisplayName: property.ContainingType.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat),
                PropertyName: property.Name,
                PropertyTypeCodeName: property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                PropertyTypeFullName: property.Type.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat),
                PropertyTypeDisplayName: property.Type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat),
                IsNullable: property.NullableAnnotation == NullableAnnotation.Annotated,
                Methods: GetInvokableMethods(property.Type)));
        }

        return builder.ToImmutable();
    }

    private static bool InheritsFromGeneratedMetadata(INamedTypeSymbol attributeType)
    {
        for (var current = attributeType.BaseType; current is not null; current = current.BaseType)
        {
            if (current.ToDisplayString() == GeneratedMetadataAttributeName)
            {
                return true;
            }
        }

        return false;
    }

    private static string GenerateSource(ImmutableArray<MetadataProperty> properties)
    {
        var attributes = properties
            .GroupBy(static property => new AttributeKey(property.AttributeTypeCodeName, property.AttributeTypeFullName))
            .OrderBy(static group => group.Key.FullName, StringComparer.Ordinal)
            .ToArray();

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine();
        source.AppendLine("namespace Long.Metadata");
        source.AppendLine("{");
        source.AppendLine("    public static class GeneratedMetadata");
        source.AppendLine("    {");
        source.AppendLine("        public static global::System.Collections.Generic.IReadOnlyList<global::Long.Metadata.GeneratedPropertyMetadata<TAttribute>> GetProperties<TAttribute>()");
        source.AppendLine("            where TAttribute : global::Long.Metadata.GeneratedMetadataAttribute");
        source.AppendLine("        {");

        foreach (var group in attributes)
        {
            source.Append("            if (typeof(TAttribute) == typeof(");
            source.Append(group.Key.CodeName);
            source.AppendLine("))");
            source.AppendLine("            {");
            source.Append("                return (global::System.Collections.Generic.IReadOnlyList<global::Long.Metadata.GeneratedPropertyMetadata<TAttribute>>)(object)");
            source.Append(GetFieldName(group.Key.FullName));
            source.AppendLine(";");
            source.AppendLine("            }");
            source.AppendLine();
        }

        source.AppendLine("            return global::System.Array.Empty<global::Long.Metadata.GeneratedPropertyMetadata<TAttribute>>();");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        public static global::System.Collections.Generic.IReadOnlyList<global::Long.Metadata.GeneratedPropertyMetadata> GetAllProperties()");
        source.AppendLine("        {");
        source.AppendLine("            return __AllProperties;");
        source.AppendLine("        }");
        source.AppendLine();

        foreach (var group in attributes)
        {
            source.Append("        private static readonly global::Long.Metadata.GeneratedPropertyMetadata<");
            source.Append(group.Key.CodeName);
            source.Append(">[] ");
            source.Append(GetFieldName(group.Key.FullName));
            source.AppendLine(" = new global::Long.Metadata.GeneratedPropertyMetadata<" + group.Key.CodeName + ">[]");
            source.AppendLine("        {");

            foreach (var property in group)
            {
                source.Append("            new global::Long.Metadata.GeneratedPropertyMetadata<");
                source.Append(group.Key.CodeName);
                source.Append(">(");
                AppendString(source, property.DeclaringTypeFullName);
                source.Append(", ");
                AppendString(source, property.DeclaringTypeDisplayName);
                source.Append(", ");
                AppendString(source, property.PropertyName);
                source.Append(", ");
                AppendString(source, property.PropertyTypeFullName);
                source.Append(", ");
                AppendString(source, property.PropertyTypeDisplayName);
                source.Append(", ");
                source.Append(property.IsNullable ? "true" : "false");
                if (property.Methods.Length > 0)
                {
                    source.Append(", ");
                    source.Append(GetInvokerName(property));
                }

                source.AppendLine("),");
            }

            source.AppendLine("        };");
            source.AppendLine();
        }

        foreach (var property in properties.Where(static property => property.Methods.Length > 0))
        {
            source.Append("        private static object? ");
            source.Append(GetInvokerName(property));
            source.AppendLine("(object declaringInstance, string methodName)");
            source.AppendLine("        {");
            source.Append("            var propertyValue = ((");
            source.Append(property.DeclaringTypeCodeName);
            source.Append(")declaringInstance).");
            source.Append(EscapeIdentifier(property.PropertyName));
            source.AppendLine(";");
            source.AppendLine("            if (propertyValue is null)");
            source.AppendLine("            {");
            source.AppendLine("                return null;");
            source.AppendLine("            }");
            source.AppendLine();
            source.AppendLine("            switch (methodName)");
            source.AppendLine("            {");

            foreach (var method in property.Methods)
            {
                source.Append("                case ");
                AppendString(source, method.Name);
                source.AppendLine(":");

                if (method.ReturnsVoid)
                {
                    source.Append("                    propertyValue.");
                    source.Append(EscapeIdentifier(method.Name));
                    source.AppendLine("();");
                    source.AppendLine("                    return null;");
                }
                else
                {
                    source.Append("                    return propertyValue.");
                    source.Append(EscapeIdentifier(method.Name));
                    source.AppendLine("();");
                }
            }

            source.AppendLine("                default:");
            source.AppendLine("                    throw new global::System.MissingMethodException(\"Generated method metadata was not found for method '\" + methodName + \"'.\");");
            source.AppendLine("            }");
            source.AppendLine("        }");
            source.AppendLine();
        }

        source.AppendLine("        private static readonly global::Long.Metadata.GeneratedPropertyMetadata[] __AllProperties = new global::Long.Metadata.GeneratedPropertyMetadata[]");
        source.AppendLine("        {");

        foreach (var property in properties)
        {
            source.Append("            new global::Long.Metadata.GeneratedPropertyMetadata(");
            AppendString(source, property.DeclaringTypeFullName);
            source.Append(", ");
            AppendString(source, property.DeclaringTypeDisplayName);
            source.Append(", ");
            AppendString(source, property.PropertyName);
            source.Append(", ");
            AppendString(source, property.PropertyTypeFullName);
            source.Append(", ");
            AppendString(source, property.PropertyTypeDisplayName);
            source.Append(", ");
            source.Append(property.IsNullable ? "true" : "false");
            source.Append(", ");
            AppendString(source, property.AttributeTypeFullName);
            source.AppendLine("),");
        }

        source.AppendLine("        };");
        source.AppendLine("    }");
        source.AppendLine("}");

        return source.ToString();
    }

    private static ImmutableArray<InvokableMethod> GetInvokableMethods(ITypeSymbol propertyType)
    {
        if (propertyType is not INamedTypeSymbol namedType || !namedType.IsReferenceType || namedType.SpecialType == SpecialType.System_String)
        {
            return ImmutableArray<InvokableMethod>.Empty;
        }

        return namedType.GetMembers()
            .OfType<IMethodSymbol>()
            .Where(static method =>
                method.MethodKind == MethodKind.Ordinary &&
                method.DeclaredAccessibility == Accessibility.Public &&
                !method.IsStatic &&
                !method.IsGenericMethod &&
                !method.ReturnsByRef &&
                !method.ReturnsByRefReadonly &&
                method.Parameters.Length == 0 &&
                method.ContainingType.SpecialType != SpecialType.System_Object)
            .GroupBy(static method => method.Name, StringComparer.Ordinal)
            .Where(static group => group.Count() == 1)
            .Select(static group => group.Single())
            .OrderBy(static method => method.Name, StringComparer.Ordinal)
            .Select(static method => new InvokableMethod(
                method.Name,
                method.ReturnType.SpecialType == SpecialType.System_Void))
            .ToImmutableArray();
    }

    private static string GetFieldName(string attributeTypeFullName)
    {
        var builder = new StringBuilder("__");
        foreach (var character in attributeTypeFullName)
        {
            builder.Append(char.IsLetterOrDigit(character) ? character : '_');
        }

        return builder.ToString();
    }

    private static string GetInvokerName(MetadataProperty property)
    {
        return GetFieldName($"{property.DeclaringTypeFullName}.{property.PropertyName}.Invoker");
    }

    private static string EscapeIdentifier(string identifier)
    {
        return SyntaxFacts.GetKeywordKind(identifier) == SyntaxKind.None &&
            SyntaxFacts.GetContextualKeywordKind(identifier) == SyntaxKind.None
            ? identifier
            : "@" + identifier;
    }

    private static void AppendString(StringBuilder source, string value)
    {
        source.Append("@\"");
        source.Append(value.Replace("\"", "\"\""));
        source.Append('"');
    }

    private readonly record struct AttributeKey(string CodeName, string FullName);

    private readonly record struct MetadataProperty(
        string Key,
        string AttributeTypeCodeName,
        string AttributeTypeFullName,
        string DeclaringTypeCodeName,
        string DeclaringTypeFullName,
        string DeclaringTypeDisplayName,
        string PropertyName,
        string PropertyTypeCodeName,
        string PropertyTypeFullName,
        string PropertyTypeDisplayName,
        bool IsNullable,
        ImmutableArray<InvokableMethod> Methods);

    private readonly record struct InvokableMethod(string Name, bool ReturnsVoid);
}
